# Generated by Django 4.2.4 on 2023-08-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptoApp", "0003_alter_watchlistmodel_coinname"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlistmodel",
            name="coinImg",
            field=models.CharField(default="test", max_length=1000),
        ),
    ]
